_wandb:
    value:
        cli_version: 0.23.0
        e:
            fyg43w2z2wff5iac0ko6xblomu39msyf:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "15032385536"
                codePath: /Users/mahdy/projects/computer_vision_yolo/quick_test/yolo_quick_test.ipynb
                codePathLocal: yolo_quick_test.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "378477289472"
                email: m3edris@gmail.com
                executable: /Users/mahdy/projects/computer_vision_yolo/yolo_project/bin/python
                git:
                    commit: aea7caaf80c76d48fc618e4412b49286b63ee910
                    remote: https://github.com/m3mahdy/computer_vision_yolo.git
                host: Mohammeds-MacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/mahdy/projects/computer_vision_yolo/quick_test/yolo_quick_test.ipynb
                python: CPython 3.12.3
                root: /Users/mahdy/projects/computer_vision_yolo/quick_test
                startedAt: "2025-11-20T23:52:44.508401Z"
                writerId: fyg43w2z2wff5iac0ko6xblomu39msyf
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.3
            "5": 0.23.0
            "8":
                - 1
            "12": 0.23.0
            "13": darwin-arm64
dataset:
    value: bdd100k_tmp_images_limited
flops_gflops:
    value: 0
iou_threshold:
    value: 0.5
model:
    value: yolov9s
model_params:
    value: 7318368
model_size_mb:
    value: 14.674522399902344
num_classes:
    value: 10
split:
    value: test
